import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import "aos/dist/aos.css";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`p-antialiased text-p_black`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
